### ISSUE TITLE
ad9361_dig_tune_delay: Tuning RX FAILED! 

### ISSUE THREAD

**Issue by qianshuyuank** [MicroPhase/antsdr_standalone#3]
AD9361 初始化失败怎么做

SAMPL CLK: 61440000 tuning: RX
  0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:
0:# # # # # # # # # # # # # # # # 
1:# # # # # # # # # # # # # # # # 
ad9361_dig_tune_delay: Tuning RX FAILED!
ad9361_init : AD936x initialization error
Failed to restore state
Failed to restore state

**Comment by black-pigeon** [comment]
你是直接用的这个工程吗，这个和接口调谐有关系，我们的硬件我们在裸机上测试过使用2r2t模式在61.44M采样率下，接口调谐都是可以通过的。关于接口的调谐，你可以参考下面的连接：https://wiki.analog.com/resources/eval/user-guides/ad-fmcomms2-ebz/interface_timing_validation?s

**Comment by qianshuyuank** [comment]
SAMPL CLK: 25000000 tuning: RX
  0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:
0:# # # # # # # # # # # # # # # # 
1:# # # # # # # # # # # # # # # # 
SAMPL CLK: 40000000 tuning: RX
  0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:
0:# # # # # # # # # # # # # # # # 
1:# # # # # # # # # # # # # # # # 
SAMPL CLK: 61440000 tuning: RX
  0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:
0:# # # # # # # # # # # # # # # # 
1:# # # # # # # # # # # # # # # # 
SAMPL CLK: 61440000 tuning: RX
  0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:
0:# # # # # # # # # # # # # # # # 
1:# # # # # # # # # # # # # # # # 
ad9361_dig_tune_delay: Tuning RX FAILED!
ad9361_init : AD936x initialization error
Failed to restore state
Failed to restore state
跳过调谐吗？为什么没有pass项

**Comment by qianshuyuank** [comment]
手头上有vivado191.的环境，一开始用的 antsdr-fw 中的项目中 HDL编译的，一直没找到问题原因。后来更换为18.3 按照说明编译测试通过。两个HDL程序不一样，让我困惑了好长时间
